#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Generador Masivo de Tarjetas Editables
Procesa múltiples tarjetas en formato PDF editable
"""

import csv
import os
from generador_editable import generar_tarjeta_editable

def generar_masivo_editable(nombres, cargos):
    """
    Genera tarjetas editables desde dos listas: nombres y cargos
    
    Args:
        nombres: Lista de nombres
        cargos: Lista de cargos (debe tener la misma longitud que nombres)
    """
    if len(nombres) != len(cargos):
        print("✗ Error: Las listas de nombres y cargos deben tener la misma longitud")
        return
    
    tarjetas_generadas = 0
    errores = 0
    
    print("=" * 60)
    print(" GENERACIÓN MASIVA DE TARJETAS EDITABLES (PDF)")
    print("=" * 60)
    print()
    
    for i, (nombre, cargo) in enumerate(zip(nombres, cargos), 1):
        nombre = nombre.strip()
        cargo = cargo.strip()
        
        if not nombre or not cargo:
            print(f"⚠ Entrada {i}: Datos incompletos - saltando")
            errores += 1
            continue
        
        print(f"\n[{i}/{len(nombres)}] Generando: {nombre}")
        resultado = generar_tarjeta_editable(nombre, cargo)
        
        if resultado:
            tarjetas_generadas += 1
        else:
            errores += 1
    
    print("\n" + "=" * 60)
    print(f"✓ Proceso completado:")
    print(f"  - Tarjetas generadas: {tarjetas_generadas}")
    if errores > 0:
        print(f"  - Errores: {errores}")
    print("=" * 60)
    print("\n✓ Para editar el texto:")
    print("  1. Abra el PDF en Adobe Acrobat")
    print("  2. Vaya a Herramientas > Editar PDF")
    print("  3. Haga clic en el texto para editarlo")

# ============================================================
# CONFIGURACIÓN - LISTAS DE NOMBRES Y CARGOS
# ============================================================

# Nombres de los colaboradores
NOMBRES = """
DEUDOR MORENO CHRISTIAN SEBASTIAN
MORENO VALVERDE GUILDA CLEMENTINA
VELA GUTIERREZ JOSE EDUARDO
FALCIATORE ROJAS DANTE
LINDLEY PEREZ CARLOS ERNESTO
NAVARRO FERREYRA PAOLA MILAGROS
PANTA MENA MARIA MAGDALENA
PAREDES BENITO ROGER SAUL
SANCHEZ PALOMINO MARCOS FABIANNI
SILVA MADUEÑO ALEX
DUEÑAS CARITAS EDWARS RICHARD
MERCADO NAVARRO CARLOMAN ELKIN
ESCOBAR GUTIERREZ JONATHAN FELIX
HORNA NUÑUVERO JOHAN ISRAEL
COTRINA RODRIGUEZ JUAN ALEJANDRO
FLORES INCA ALEJANDRO
MALPARTIDA QUIJANDRIA MANUEL
ARELLANO PALACIOS ELVIS ERNESTO
ALCOCER RIVERA CALEB JACOB FRANCISCO
LIZARRAGA CASAS OMAR MARIO
QUISPE JAVIER MARIORY ALEJANDRA
BARREZUETA OLARTE LUCIA GIANELLE
ROSERO SILVA JUAN
PALOMINO GAMARRA PAOLA GISELLE
GARCIA COVEÑA PERCY MARTIN
SALAZAR FERNANDEZ MARICIELO CARMEN
RODRIGUEZ CAYOMA CARLOS ALBERTO
CARRANZA BONILLA MARIA ESTELA
HUAMAN REYES DENNIS ALEXANDER
CAYCHO LLANOS JOSE CARLOS
VEXLER NAMER ALBERTO LEIB
SANCHEZ ARIAS ANGHELA LIZETH
RUIZ VARILLAS CHRISTIAN CARLOS
ENRIQUEZ HUARIPAUCAR JULIO CESAR
ZEA JIMENEZ LUIS CARLOS
VILLANUEVA ROSALES YULY YASMIN
PASCO BODERO CESAR ENRIQUE
DIAZ CABRERA NATALY BRENDA
LOPEZ TAPIA SAMUEL
GUTIERRREZ LI HUMBER ALDAIR
MOSTACERO TRUJILLO JUAN CARLOS
VERA VELARDE HENRY DAVID
CHAMBA JUAREZ JHONATAN
ISUSQUIZA CAMACHO JUAN CARLOS
CAVERO PEÑA CARLOS DAVID
MORA CONZA JUAN LEONARDO
FARFAN BARRIENTOS GUILBER MANUEL
FELIX ROMAN FREDDY MIGUEL
JESUS QUISPE SAMIR JAIME
DAVILA VIDEIRA JACKELINE ESTEPHANIE
FERREYROS ERAUSQUIN GIOVANNA MARIA
SHAPIAMA MUÑOZ JERCY
FLORES ROCHABRUNT JUAN EDMUNDO
MANCO OLIVEROS JHERSON EDUARDO
PEREZ HUAYHUAMEZA JOSE GABRIEL
QUEREVALU DELGADO JULISSA VANESSA
VIDAL VIDAL JOSE RICARDO
CANDELA HERNANDEZ JORGE ENRRIQUE
GUTIERREZ YOZA ERNESTO RAUL
SALAZAR MARREROS ANDREA PATRICIA
PEÑA ESPINOZA WALTER ORLANDO
GONZALES SANAVIA JORGE LUIS
VIZARRETA DELGADO GINA ROSA
POLLERA JARA EDUARDO
TARAZONA BENDEZU GINA YECIFER
DELGADO BUSTAMANTE MIGUEL GUSTAVO
HUAMAN LLIUYACE ANDERSON ENRIQUE
MONTOYA CRIBILLEROS LUIS GIANCARLOS
GUERRERO CRUZADA SAMUEL
TRIGOSO DAVILA LUIGI LUGO
INQUIL ORTIZ RONALD NILS
SALAS RIVAROLA ALVARO RENZO
VILLAVICENCIO KAQUI PAOLO ALBERTO
ARELLANO BLAS SUSANA
ECHAVARRIA ROJAS ABIMAEL
RAMIREZ ORTEGA NILO
HUANILO PEREZ ROSARIO KATHERINE
ZEGARRA BISBAL DHAJANA ABIGAIL
CHUQUIURI LUNA JOSE EDUARDO
CASTAÑEDA CARPIO MARCO ANTONIO
ISIDRO VENTURA MARIA DEL PILAR
TORRES PACUNDA RODIN
CUELLAR DAMAZO JOSE FELIX
SANCHEZ YUPANQUI RONALD ALEX
ESPINOZA LOYOLA FIDEL MICHAEL
MOLINA ZEA SULAY KARELYN
SEMINARIO ATKINS LUIS FELIPE
VERGARA MOSCOSO CESAR
HIDALGO ZEVALLOS EDGAR MARTIN
HERVIAS AGUILAR JULIO CESAR
HINOJOSA KÚ ADRIAN ARMANDO
RIOS AGUILERA FRANKLIN AURELIANO
SOSA MATUTE OSCAR MARTIN
LOPEZ CULQUICONDOR HENRY EDWARD
MONTOYA KOO STEFFANY CAROLINA
ROMERO VALDERRAMA EDUARDO JEUNER
CULQUI VASQUEZ EDIN LUIS
MARCOS VELASQUEZ MARIA ESTHER
FLORES LLONTOP GUILLERMO MARCELINO
ARROYO GARCIA MARK ANTHONY
JULCA FELIPE GEYSON RONALD
SARAVIA JUAREZ JOSE ALBERTO
GONZALES MEZA ROSSMERY
BOUVERIE COLMENARES VERONICA CARMEN
MENDOZA MORENO JUAN CARLOS
MONTAÑEZ PEREZ KATHERINE PIERINA
HERMOZA AMBICHO JOSE DANIEL
""".strip()

# Cargos de los colaboradores
CARGOS = """
ANALISTA DE GESTIÓN
ASISTENTE DE CONTABILIDAD
JEFE DE VENTAS
COORDINADOR DE MANTENIMIENTO
JEFE DE SEGURIDAD Y PREVENCIOÓN
EJECUTIVO DEL SERVICIO AL CLIENTE
ASISTENTE ADMINISTRATIVO
AUXILIAR DE GESTIÓN
ADMINISTRADOR DE CENTRO LOGISTICO
OPERADOR DE CENTRO DE CONTROL
COORDINADOR DE SEGURIDAD ELECTRÓNICA
OPERADOR DE MANTENIMIENTO PREVENTIVO
ADMINITRADOR DE CENTRO LOGISTICO
CONTROLADOR DE SEGURIDAD
OPERADOR DE CENTRO DE CONTROL
OPERADOR DE MANTENIMIENTO
COORDINADOR DE PREVENCIÓN
SUB ADMINISTRADOR DE CENTRO LOGISTICO
COORDINADOR DE ELECTRICIDAD
AUXILIAR DE ALMACEN
PRACTICANTE DE GESTIÓN ADMINISTRATIVA Y FINANCIERA
DISEÑADOR GRAFICO JUNIOR
OPERADOR DE MANTENIMIENTO
JEFE DE VENTAS
SUPERVISOR DE ELECTRICIDAD
PRACTICANTE DE SOSTENIBILIDAD
OPERADOR DE GARITA
ANALISTA DE RECURSOS HUMANOS
OPERADOR DE CENTRO DE CONTROL
SUB ADMINISTRADOR DE CENTRO LOGISTICO
GERENTE COMERCIAL
ANALISTA DE SISTEMAS
JEFE DE RECURSOS HUMANOS
OPERADOR DE PATIO
SUPERVISOR DE ADQUISICIONES
ANALISTA SENIOR DE GESTIÓN
GERENTE CORPORATIVO DE FINANZAS
AUXILIAR ADMINISTRATIVO
CONTROLADOR DE SEGURIDAD
AUXILIAR DE OBRAS Y PROYECTOS
JEFE DE OBRAS Y PROYECTOS
OPERADOR DE CENTRO DE CONTROL
OPERADOR DE CENTRO DE CONTROL
SUB ADMINISTRADOR DE CENTRO LOGISTICO
ANALISTA SENIOR DE GESTIÓN
OPERADOR DE CENTRO DE CONTROL
COORDINADOR DE SOPORTE Y PLATAFORMA
COORDINADOR DE FACTURACIÓN Y COBRANZAS
OPERADOR DE MANTENIMIENTO ELÉCTRICO
AUXILIAR DE FACTURACIÓN Y COBRANZAS
AUXILIAR DE FACTURACIÓN Y COBRANZAS
OPERADOR DE MANTENIMIENTO DE OBRAS Y REPARACIONES
JEFE DE OPERACIONES
OPERADOR DE CENTRO DE CONTROL
ADMINISTRADOR DE CENTRO LOGISTICO
SUPERVISOR DE SOSTENIBILIDAD
SUPERVISOR DE OBRAS Y REPARACIONES
SUPERVISOR DE MANTENIMIENTO PREVENTIVO
GERENTE DE ADMINISTRACIÓN Y FINANZAS
PRACTICANTE DE OPERACIONES
OPERADOR DE GARITA
ADMINISTRADOR DE CENTRO LOGISTICO
ASISTENTE DE GERENCIA GENERAL
SUB CONTADOR
ANALISTA DE FACTURACIÓN Y COBRANZAS
SUPERVISOR DE FACTURACIÓN Y COBRANZAS
OPERADOR DE CENTRO DE CONTROL
TECNICO INFORMATICO
OPERADOR DE CENTRO DE CONTROL
SUPERVISOR TÉCNICO DE OBRA
COORDINADOR DE SEGURIDAD FÍSICA
GERENTE DE OPERACIONES
JEFE DE MARKETING
JEFE DE TECNOLOGÍAS DE LA INFORMACIÓN
SUB ADMINISTRADOR DE CENTRO LOGISTICO
COORDINADOR DE PREVENCIÓN
SUPERVISOR DE GESTIÓN DE LA CALIDAD
AUXILIAR DE TESORERIA
OPERADOR DE MANTENIMIENTO PREVENTIVO
ANALISTA SENIOR DE GESTIÓN ADMINISTRATIVA Y FINANCIERA
COORDINADOR DE OBRAS Y REPARACIONES
OPERADOR DE GARITA
COORDINADOR DE ELECTRICIDAD
OPERADOR DE CENTRO DE CONTROL
COORDINADOR DE MANTENIMIENTO PREVENTIVO
RECEPCIONISTA
GERENTE GENERAL
OPERADOR DE MANTENIMIENTO DE OBRAS Y REPARACIONES
OPERADOR DE MANTENIMIENTO DE OBRAS Y REPARACIONES
CONTADOR GENERAL
ANALISTA DE SISTEMAS
OPERADOR DE GARITA
GERENTE DE DESARROLLO DE NEGOCIOS
JEFE DE OPERACIONES ALG
COORDINADOR DE ALMACENES
CONTROLADOR DE SEGURIDAD
OPERADOR DE MANTENIMIENTO ADMINISTRATIVO
ASISTENTE CONTABLE
ADMINISTRADOR DE CENTRO LOGÍSTICO
SUPERVISOR DE PROYECTOS DE TECNOLOGÍAS DE LA INFORMACIÓN
SUPERVISOR DE SEGURIDAD ELECTRÓNICA
SUB ADMINISTRADOR DE CENTRO LOGÍSTICO
TESORERO
COORDINADOR DE ALMACENES
CONTROLADOR DE GARITA
ASISTENTE CONTABLE
ASISTENTE CONTABLE
""".strip()

if __name__ == "__main__":
    lista_nombres = [n.strip() for n in NOMBRES.split('\n') if n.strip()]
    lista_cargos = [c.strip() for c in CARGOS.split('\n') if c.strip()]
    
    # Verificar que coincidan las cantidades
    if len(lista_cargos) < len(lista_nombres):
        print(f"⚠ Advertencia: Solo hay {len(lista_cargos)} cargos para {len(lista_nombres)} nombres")
        print("Por favor, complete la lista de cargos en el archivo.")
    else:
        generar_masivo_editable(lista_nombres, lista_cargos)
